source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target ‘QSAMusic’ do
pod 'SDWebImage', '~> 3.7.6'
pod 'Alamofire', '~> 4.4'
pod 'iCarousel', '~> 1.8.2'
pod 'FXImageView', '~> 1.3.5'
pod 'pop’, '~> 1.0.9’

end
