source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target 'QSMusicDemo_OC’ do
pod 'iCarousel', '~> 1.8.2'
pod 'SDWebImage', '~> 3.8.1'
pod 'FXImageView', '~> 1.3.5'
pod 'pop', '~>1.0.9'
pod 'MagicalRecord', '~> 2.3.2'
pod 'TheAmazingAudioEngine', '~> 1.5.6'

end
